"""Add arrival_status, arrival_time, checked_in_by to appointments

Revision ID: ee5962914f10
Revises: cfb00ab31896
Create Date: 2025-11-30 17:47:18.123456

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ee5962914f10'
down_revision = 'cfb00ab31896'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrival_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('arrival_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('checked_in_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_appointments_checked_in_by', 'user', ['checked_in_by'], ['id'])

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointments_checked_in_by', type_='foreignkey')
        batch_op.drop_column('checked_in_by')
        batch_op.drop_column('arrival_time')
        batch_op.drop_column('arrival_status')

    # ### end Alembic commands ###
